server:
  port: 8080
spring:
  application:
    name: product-ms

  datasource:
    url: jdbc:postgresql://localhost:5435/${db.name:productdb}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  cache:
    type: CAFFEINE

  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%X{correlationId}]){blue} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"

