server:
  port: 8080
spring:
  application:
    name: product-ms

  datasource:
    url: ${database-url}
    username: ${db-username}
    password: ${db-password}
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: false
      password: false

  cache:
    type: CAFFEINE

  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
      
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-format: iso
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%X{correlationId}]){blue} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"

